name: Déploiement

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: http://toto.fr

    steps:
      - name: deploiement
        # ...
